name: higher-education-simulation
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - ipykernel
  - nb_conda
  - jupyter_contrib_nbextensions
  - "dvc[gdrive]"
  - isort
  - nbdime
  - scikit-learn

