name: higher-education-simulation
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyter
  - ipykernel
  - nb_conda
  - jupyter_contrib_nbextensions
  - "dvc[gdrive]"
  - isort
  - nbdime
  - scikit-learn
  - pyspark
  - pyarrow
  - conda-pack
  - seaborn
  - matplotlib
  - ipywidgets
  - shap


